pub const USER_ALREADT_EXIST: &str = "User already exists";
pub const USER_NOT_FOUND: &str = "User is not found";
pub const UNAUTHORIZED: &str = "User unauthorized";
pub const INVALID_PASSWORD: &str = "Password invalid";
pub const TOKEN_GENERATION_ERROR: &str = "Token generation error";
pub const TOKEN_VALIDATION_ERROR: &str = "Token validation error";
pub const PASSWORD_VERIFICATION_ERROR: &str = "Password verification error";
pub const PASSWORD_HASHING_ERROR: &str = "Password hashing error";
pub const UNEXPECT_DB_ERROR: &str = "Unexpect database error";
